name: ğŸš€ Build and Archive Nuxt.js Site

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v2

      - name: ğŸ§¶ Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Oder eine andere Node-Version, die dein Projekt benÃ¶tigt

      - name: ğŸ“¦ Install Dependencies
        run: npm install
        working-directory: ./development/fw-frontend # Wechsle ins Frontend-Verzeichnis

      - name: âš™ï¸ Build Nuxt.js Project
        run: npm run build
        working-directory: ./development/fw-frontend # Wechsle ins Frontend-Verzeichnis

      - name: ğŸ—‚ï¸ Prepare Archive
        run: |
          # Das generierte `dist` Verzeichnis von Nuxt.js befindet sich innerhalb des Frontend-Verzeichnisses
          cp -R ./development/fw-frontend/.nuxt/dist/client/ dist/ # Kopiere den Inhalt von `.nuxt/dist/client/` nach `dist/`
          # Falls du statische Dateien hast, die kopiert werden mÃ¼ssen, kannst du sie hier hinzufÃ¼gen.
          # Zum Beispiel:
          # cp -R ./development/fw-frontend/static/* dist/

      - name: ğŸ“¦ Archive Website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/
