name: ğŸš€ Build and Archive Website

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v2

      - name: ğŸ—ï¸ Build Project
        run: |
          npm run dev
          mkdir -p dist/
          cp -R source/* dist/ # Ersetze 'source/' mit dem Verzeichnis deiner HTML/CSS Dateien.

      - name: ğŸ“¦ Archive Website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/
