name: ğŸš€ Build and archive Nuxt.js project

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v2

      - name: ğŸ§¶ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: ğŸ“¦ Install dependencies
        run: npm install
        working-directory: ./development/fw-frontend

      - name: âš™ï¸ Build Nuxt.js project
        run: npm run build
        working-directory: ./development/fw-frontend

      - name: ğŸ—‚ï¸ Prepare archive
        run: |
          cp -R ./development/fw-frontend/.nuxt/dist/client/ dist/ # Kopiere den Inhalt von `.nuxt/dist/client/` nach `dist/`

      - name: ğŸ“¦ Archive website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/

## Made by L50N with <3
