name: ğŸš€ Build and Archive Website

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v2
      
      - name: ğŸ—‚ï¸ Prepare Distribution Directory
        run: |
          mkdir -p dist/
          cp ./development/fw-frontend/*.html dist/ # Kopiert alle HTML-Dateien
          cp ./development/fw-frontend/*.css dist/  # Kopiert alle CSS-Dateien
          # Kopiere weitere Ressourcen wie Bilder, JS usw., falls notwendig
          cp -r ./development/fw-frontend/images dist/ # Beispiel fÃ¼r Bilder
          cp -r ./development/fw-frontend/js dist/ # Beispiel fÃ¼r JavaScript-Dateien

      - name: ğŸ“¦ Archive Website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/
