name: ğŸš€ Build and Archive Website

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v2

      - name: ğŸ—‚ï¸ Prepare Distribution Directory
        run: |
          mkdir -p dist/
          cp *.html dist/ # Kopiere alle HTML-Dateien
          cp *.css dist/ # Kopiere alle CSS-Dateien
          # FÃ¼ge hier weitere Kopierbefehle hinzu fÃ¼r andere Dateitypen, die du benÃ¶tigst, z.B. cp *.js dist/

      - name: ğŸ“¦ Archive Website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/
