name: ğŸš€ Build and Archive Website

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v2

      - name: ğŸ—‚ï¸ Prepare Distribution Directory
        run: |
          mkdir -p dist/
          cp -R * dist/ # Kopiere alle Dateien im Root-Verzeichnis

      - name: ğŸšš Exclude Non-Distributable Files
        run: |
          rm -rf dist/.git dist/.github dist/workflows # Entferne nicht benÃ¶tigte Dateien und Verzeichnisse

      - name: ğŸ“¦ Archive Website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/
