name: ğŸš€ Build and Archive Website

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v2
      
      - name: ğŸ“‚ List directory structure
        run: ls -R # Zeigt die Struktur des ausgecheckten Repositories an

      - name: ğŸ—‚ï¸ Prepare Distribution Directory
        run: |
          mkdir -p dist/
          cp src/*.html dist/ # Kopiere alle HTML-Dateien aus dem Verzeichnis 'src'
          cp src/*.css dist/ # Kopiere alle CSS-Dateien aus dem Verzeichnis 'src'
          # FÃ¼ge hier weitere Kopierbefehle hinzu fÃ¼r andere Dateitypen, die du benÃ¶tigst, z.B. cp src/*.js dist/

      - name: ğŸ“¦ Archive Website
        uses: actions/upload-artifact@v2
        with:
          name: website-artifact
          path: dist/
